"""Seed database with all stage 1 chapters (1-15) and exercises"""
from sqlalchemy.orm import Session
from app.models.chapter import Chapter
from app.models.exercise import Exercise


def seed_all(db: Session):
    """Seed chapters 1-15 and their exercises."""
    chapters_data = [
        # Stage 1: 语法基础 (15 chapters)
        {"stage": 1, "order": 1, "slug": "ch01-hello-rust", "title": "Hello Rust", "subtitle": "安装工具链，运行第一个 Rust 程序", "content_file": "chapters/01-hello-rust.md", "unlock_after": None},
        {"stage": 1, "order": 2, "slug": "ch02-variables-types", "title": "变量与类型", "subtitle": "let、mut、基本数据类型、类型推导与转换", "content_file": "chapters/02-variables-types.md", "unlock_after": "ch01-hello-rust"},
        {"stage": 1, "order": 3, "slug": "ch03-functions-control", "title": "函数与控制流", "subtitle": "fn、if/else、match、loop、while、for", "content_file": "chapters/03-functions-control.md", "unlock_after": "ch02-variables-types"},
        {"stage": 1, "order": 4, "slug": "ch04-ownership", "title": "所有权系统", "subtitle": "Rust 最核心的概念：move、clone、copy", "content_file": "chapters/04-ownership.md", "unlock_after": "ch03-functions-control"},
        {"stage": 1, "order": 5, "slug": "ch05-borrowing", "title": "引用与借用", "subtitle": "&T 和 &mut T，借用规则，生命周期初探", "content_file": "chapters/05-borrowing.md", "unlock_after": "ch04-ownership"},
        {"stage": 1, "order": 6, "slug": "ch06-structs", "title": "结构体", "subtitle": "struct 定义、方法、关联函数", "content_file": "chapters/06-structs.md", "unlock_after": "ch05-borrowing"},
        {"stage": 1, "order": 7, "slug": "ch07-enums-pattern", "title": "枚举与模式匹配", "subtitle": "enum、Option、Result、match 表达式", "content_file": "chapters/07-enums-pattern.md", "unlock_after": "ch06-structs"},
        {"stage": 1, "order": 8, "slug": "ch08-error-handling", "title": "错误处理", "subtitle": "Result、? 操作符、panic、自定义错误", "content_file": "chapters/08-error-handling.md", "unlock_after": "ch07-enums-pattern"},
        {"stage": 1, "order": 9, "slug": "ch09-collections", "title": "集合类型", "subtitle": "Vec、HashMap、String、迭代器", "content_file": "chapters/09-collections.md", "unlock_after": "ch08-error-handling"},
        {"stage": 1, "order": 10, "slug": "ch10-generics", "title": "泛型", "subtitle": "泛型函数、泛型结构体、单态化", "content_file": "chapters/10-generics.md", "unlock_after": "ch09-collections"},
        {"stage": 1, "order": 11, "slug": "ch11-traits", "title": "Trait", "subtitle": "定义 trait、实现 trait、trait bound", "content_file": "chapters/11-traits.md", "unlock_after": "ch10-generics"},
        {"stage": 1, "order": 12, "slug": "ch12-closures-iterators", "title": "闭包与迭代器", "subtitle": "Fn/FnMut/FnOnce、map/filter/fold", "content_file": "chapters/12-closures-iterators.md", "unlock_after": "ch11-traits"},
        {"stage": 1, "order": 13, "slug": "ch13-modules", "title": "模块系统", "subtitle": "mod、use、pub、crate 组织", "content_file": "chapters/13-modules.md", "unlock_after": "ch12-closures-iterators"},
        {"stage": 1, "order": 14, "slug": "ch14-cargo-ecosystem", "title": "Cargo 生态", "subtitle": "依赖管理、feature、workspace", "content_file": "chapters/14-cargo-ecosystem.md", "unlock_after": "ch13-modules"},
        {"stage": 1, "order": 15, "slug": "ch15-stage-project", "title": "阶段项目：CLI 词频统计", "subtitle": "综合运用前14章知识", "content_file": "chapters/15-stage-project.md", "unlock_after": "ch14-cargo-ecosystem"},
        # Stage 2: 系统编程 (placeholder)
        {"stage": 2, "order": 16, "slug": "ch16-smart-pointers", "title": "智能指针", "subtitle": "Box、Rc、Arc", "content_file": "chapters/16-smart-pointers.md", "unlock_after": "ch15-stage-project"},
        {"stage": 2, "order": 17, "slug": "ch17-interior-mutability", "title": "内部可变性", "subtitle": "RefCell、Mutex、RwLock", "content_file": "chapters/17-interior-mutability.md", "unlock_after": "ch16-smart-pointers"},
        {"stage": 2, "order": 18, "slug": "ch18-concurrency", "title": "并发基础", "subtitle": "thread::spawn、move 闭包", "content_file": "chapters/18-concurrency.md", "unlock_after": "ch17-interior-mutability"},
    ]

    for data in chapters_data:
        ch = Chapter(**data)
        db.add(ch)
    db.flush()

    # --- Exercises for Ch1-5 (existing) ---
    ch1 = db.query(Chapter).filter(Chapter.slug == "ch01-hello-rust").first()
    exercises_ch1 = [
        {"chapter_id": ch1.id, "order": 1, "type": "free", "title": "Hello World", "description": "编写一个程序，输出 `Hello, Rust!`。", "template_code": 'fn main() {\n    // 在这里写代码\n    \n}\n', "test_code": "", "solution_code": 'fn main() {\n    println!("Hello, Rust!");\n}\n', "hint": "使用 `println!` 宏来打印文本"},
        {"chapter_id": ch1.id, "order": 2, "type": "output", "title": "println! 格式化", "description": "阅读代码，预测输出结果。", "template_code": 'fn main() {\n    let name = "Rust";\n    let year = 2015;\n    println!("Hello, {}! Born in {}", name, year);\n}\n', "test_code": "", "solution_code": "Hello, Rust! Born in 2015", "hint": "println! 会把 `{}` 替换成后面的变量值"},
    ]

    ch2 = db.query(Chapter).filter(Chapter.slug == "ch02-variables-types").first()
    exercises_ch2 = [
        {"chapter_id": ch2.id, "order": 1, "type": "fix", "title": "修复不可变变量", "description": "下面的代码无法编译，因为 `x` 是不可变的。请修复它。", "template_code": 'fn main() {\n    let x = 5;\n    x = 10;\n    println!("x = {}", x);\n}\n', "test_code": "", "solution_code": 'fn main() {\n    let mut x = 5;\n    x = 10;\n    println!("x = {}", x);\n}\n', "hint": "在 `let` 后面加 `mut` 关键字"},
        {"chapter_id": ch2.id, "order": 2, "type": "fill", "title": "类型标注", "description": "补全类型标注，使代码编译通过。", "template_code": 'fn main() {\n    let age: /* 填入类型 */ = 25;\n    let height: /* 填入类型 */ = 1.75;\n    let name: /* 填入类型 */ = "Alice";\n    let is_student: /* 填入类型 */ = true;\n    println!("{}: age={}, height={}, student={}", name, age, height, is_student);\n}\n', "test_code": "", "solution_code": 'fn main() {\n    let age: i32 = 25;\n    let height: f64 = 1.75;\n    let name: &str = "Alice";\n    let is_student: bool = true;\n    println!("{}: age={}, height={}, student={}", name, age, height, is_student);\n}\n', "hint": "整数用 i32，浮点用 f64，字符串用 &str，布尔用 bool"},
    ]

    ch3 = db.query(Chapter).filter(Chapter.slug == "ch03-functions-control").first()
    exercises_ch3 = [
        {"chapter_id": ch3.id, "order": 1, "type": "free", "title": "FizzBuzz", "description": "打印 1-30，3的倍数输出 Fizz，5的倍数输出 Buzz，15的倍数输出 FizzBuzz。", "template_code": 'fn main() {\n    for i in 1..=30 {\n        // 在这里实现 FizzBuzz\n        \n    }\n}\n', "test_code": "", "solution_code": 'fn main() {\n    for i in 1..=30 {\n        match (i % 3, i % 5) {\n            (0, 0) => println!("FizzBuzz"),\n            (0, _) => println!("Fizz"),\n            (_, 0) => println!("Buzz"),\n            _ => println!("{}", i),\n        }\n    }\n}\n', "hint": "试试 `match` 表达式配合元组匹配"},
        {"chapter_id": ch3.id, "order": 2, "type": "fix", "title": "修复函数签名", "description": "函数缺少返回类型标注，请修复。", "template_code": 'fn add(a: i32, b: i32) {\n    a + b\n}\n\nfn main() {\n    let result = add(3, 5);\n    println!("3 + 5 = {}", result);\n}\n', "test_code": "", "solution_code": 'fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n\nfn main() {\n    let result = add(3, 5);\n    println!("3 + 5 = {}", result);\n}\n', "hint": "函数最后一个表达式（不带分号）就是返回值，但需要标注返回类型"},
    ]

    ch4 = db.query(Chapter).filter(Chapter.slug == "ch04-ownership").first()
    exercises_ch4 = [
        {"chapter_id": ch4.id, "order": 1, "type": "fix", "title": "所有权转移", "description": "代码使用了已被 move 的变量，请用 clone 修复。", "template_code": 'fn main() {\n    let s1 = String::from("hello");\n    let s2 = s1;\n    println!("s1 = {}", s1);\n}\n', "test_code": "", "solution_code": 'fn main() {\n    let s1 = String::from("hello");\n    let s2 = s1.clone();\n    println!("s1 = {}", s1);\n}\n', "hint": "用 `.clone()` 深拷贝"},
        {"chapter_id": ch4.id, "order": 2, "type": "output", "title": "Copy vs Move", "description": "预测输出。", "template_code": 'fn main() {\n    let a = 42;\n    let b = a;\n    println!("a = {}, b = {}", a, b);\n\n    let s1 = String::from("hello");\n    let s2 = s1;\n    println!("s2 = {}", s2);\n}\n', "test_code": "", "solution_code": "a = 42, b = 42\ns2 = hello", "hint": "i32 是 Copy，String 不是"},
    ]

    ch5 = db.query(Chapter).filter(Chapter.slug == "ch05-borrowing").first()
    exercises_ch5 = [
        {"chapter_id": ch5.id, "order": 1, "type": "fix", "title": "可变引用规则", "description": "同一作用域不能有两个可变引用。修复代码。", "template_code": 'fn main() {\n    let mut s = String::from("hello");\n    let r1 = &mut s;\n    let r2 = &mut s;\n    println!("{}, {}", r1, r2);\n}\n', "test_code": "", "solution_code": 'fn main() {\n    let mut s = String::from("hello");\n    {\n        let r1 = &mut s;\n        println!("{}", r1);\n    }\n    let r2 = &mut s;\n    println!("{}", r2);\n}\n', "hint": "用花括号分隔作用域"},
        {"chapter_id": ch5.id, "order": 2, "type": "free", "title": "实现计算长度的函数", "description": "接收 String 的引用，返回长度。", "template_code": 'fn calculate_length(/* 参数 */) -> /* 返回类型 */ {\n    // 你的代码\n}\n\nfn main() {\n    let s = String::from("hello");\n    let len = calculate_length(/* 传参 */);\n    println!("\"{}\" 的长度是 {}", s, len);\n}\n', "test_code": "", "solution_code": 'fn calculate_length(s: &String) -> usize {\n    s.len()\n}\n\nfn main() {\n    let s = String::from("hello");\n    let len = calculate_length(&s);\n    println!("\"{}\" 的长度是 {}", s, len);\n}\n', "hint": "使用 `&String` 作为参数类型"},
    ]

    # --- Ch6-15 exercises ---
    ch6 = db.query(Chapter).filter(Chapter.slug == "ch06-structs").first()
    exercises_ch6 = [
        {"chapter_id": ch6.id, "order": 1, "type": "free", "title": "定义 Rectangle 结构体", "description": "定义一个 Rectangle 结构体，包含 width 和 height 字段，实现计算面积的方法。", "template_code": '// 定义 Rectangle 结构体\n\n\nfn main() {\n    let rect = Rectangle { width: 30, height: 50 };\n    println!("面积 = {}", rect.area());\n}\n', "test_code": "", "solution_code": 'struct Rectangle {\n    width: f64,\n    height: f64,\n}\n\nimpl Rectangle {\n    fn area(&self) -> f64 {\n        self.width * self.height\n    }\n}\n\nfn main() {\n    let rect = Rectangle { width: 30.0, height: 50.0 };\n    println!("面积 = {}", rect.area());\n}\n', "hint": "用 `struct` 定义结构体，`impl` 实现方法"},
        {"chapter_id": ch6.id, "order": 2, "type": "fix", "title": "修复方法调用", "description": "代码中的方法调用有误，请修复。", "template_code": 'struct Point {\n    x: f64,\n    y: f64,\n}\n\nimpl Point {\n    fn distance(&self, other: Point) -> f64 {\n        ((self.x - other.x).powi(2) + (self.y - other.y).powi(2)).sqrt()\n    }\n}\n\nfn main() {\n    let p1 = Point { x: 0.0, y: 0.0 };\n    let p2 = Point { x: 3.0, y: 4.0 };\n    println!("距离 = {}", p1.distance(p2));\n    println!("p1 = ({}, {})", p1.x, p1.y);\n    println!("p2 = ({}, {})", p2.x, p2.y);\n}\n', "test_code": "", "solution_code": 'struct Point {\n    x: f64,\n    y: f64,\n}\n\nimpl Point {\n    fn distance(&self, other: &Point) -> f64 {\n        ((self.x - other.x).powi(2) + (self.y - other.y).powi(2)).sqrt()\n    }\n}\n\nfn main() {\n    let p1 = Point { x: 0.0, y: 0.0 };\n    let p2 = Point { x: 3.0, y: 4.0 };\n    println!("距离 = {}", p1.distance(&p2));\n    println!("p1 = ({}, {})", p1.x, p1.y);\n    println!("p2 = ({}, {})", p2.x, p2.y);\n}\n', "hint": "调用后 p2 被 move 了，后面不能再用。改成传引用 `&Point`"},
    ]

    ch7 = db.query(Chapter).filter(Chapter.slug == "ch07-enums-pattern").first()
    exercises_ch7 = [
        {"chapter_id": ch7.id, "order": 1, "type": "free", "title": "实现 TrafficLight", "description": "定义 TrafficLight 枚举，实现 duration 方法返回每种灯的持续秒数。", "template_code": '// 定义 TrafficLight 枚举\n\n\nfn main() {\n    let red = TrafficLight::Red;\n    let green = TrafficLight::Green;\n    println!("红灯 {}秒", red.duration());\n    println!("绿灯 {}秒", green.duration());\n}\n', "test_code": "", "solution_code": 'enum TrafficLight {\n    Red,\n    Yellow,\n    Green,\n}\n\nimpl TrafficLight {\n    fn duration(&self) -> u32 {\n        match self {\n            TrafficLight::Red => 60,\n            TrafficLight::Yellow => 5,\n            TrafficLight::Green => 45,\n        }\n    }\n}\n\nfn main() {\n    let red = TrafficLight::Red;\n    let green = TrafficLight::Green;\n    println!("红灯 {}秒", red.duration());\n    println!("绿灯 {}秒", green.duration());\n}\n', "hint": "用 `enum` 定义枚举，`impl` + `match` 实现方法"},
        {"chapter_id": ch7.id, "order": 2, "type": "fix", "title": "Option 安全取值", "description": "代码用 unwrap 取 Option 值，可能 panic。改用 match 安全处理。", "template_code": 'fn find_first_even(numbers: &[i32]) -> i32 {\n    let result = numbers.iter().find(|&&x| x % 2 == 0);\n    result.unwrap() * 2\n}\n\nfn main() {\n    let nums = vec![1, 3, 5, 8, 9];\n    println!("第一个偶数的两倍 = {}", find_first_even(&nums));\n    let empty: Vec<i32> = vec![1, 3, 5];\n    println!("结果 = {}", find_first_even(&empty));\n}\n', "test_code": "", "solution_code": 'fn find_first_even(numbers: &[i32]) -> Option<i32> {\n    numbers.iter().find(|&&x| x % 2 == 0).map(|&x| x * 2)\n}\n\nfn main() {\n    let nums = vec![1, 3, 5, 8, 9];\n    match find_first_even(&nums) {\n        Some(val) => println!("第一个偶数的两倍 = {}", val),\n        None => println!("没有偶数"),\n    }\n    let empty: Vec<i32> = vec![1, 3, 5];\n    match find_first_even(&empty) {\n        Some(val) => println!("结果 = {}", val),\n        None => println!("没有偶数"),\n    }\n}\n', "hint": "返回类型改为 `Option<i32>`，用 `.map()` 转换值"},
    ]

    ch8 = db.query(Chapter).filter(Chapter.slug == "ch08-error-handling").first()
    exercises_ch8 = [
        {"chapter_id": ch8.id, "order": 1, "type": "fix", "title": "用 ? 传播错误", "description": "把 unwrap 替换成 ? 操作符来优雅处理错误。", "template_code": 'use std::fs;\n\nfn read_file() -> String {\n    let content = fs::read_to_string("test.txt").unwrap();\n    content\n}\n\nfn main() {\n    match read_file() {\n        Ok(c) => println!("{}", c),\n        Err(e) => println!("读取失败: {}", e),\n    }\n}\n', "test_code": "", "solution_code": 'use std::fs;\nuse std::io;\n\nfn read_file() -> Result<String, io::Error> {\n    let content = fs::read_to_string("test.txt")?;\n    Ok(content)\n}\n\nfn main() {\n    match read_file() {\n        Ok(c) => println!("{}", c),\n        Err(e) => println!("读取失败: {}", e),\n    }\n}\n', "hint": "函数返回类型改为 `Result<String, io::Error>`，用 `?` 替代 `unwrap`"},
        {"chapter_id": ch8.id, "order": 2, "type": "free", "title": "自定义错误类型", "description": "定义一个 AppError 枚举，包含 NotFound 和 ParseError 两种变体，实现 Display trait。", "template_code": 'use std::fmt;\n\n// 定义 AppError 枚举\n\n\nimpl fmt::Display for AppError {\n    // 实现 Display\n}\n\nfn find_user(id: u32) -> Result<String, AppError> {\n    if id == 0 {\n        Err(AppError::NotFound("用户不存在".to_string()))\n    } else {\n        Ok(format!("用户{}", id))\n    }\n}\n\nfn main() {\n    match find_user(0) {\n        Ok(name) => println!("找到: {}", name),\n        Err(e) => println!("错误: {}", e),\n    }\n}\n', "test_code": "", "solution_code": 'use std::fmt;\n\nenum AppError {\n    NotFound(String),\n    ParseError(String),\n}\n\nimpl fmt::Display for AppError {\n    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {\n        match self {\n            AppError::NotFound(msg) => write!(f, "未找到: {}", msg),\n            AppError::ParseError(msg) => write!(f, "解析错误: {}", msg),\n        }\n    }\n}\n\nfn find_user(id: u32) -> Result<String, AppError> {\n    if id == 0 {\n        Err(AppError::NotFound("用户不存在".to_string()))\n    } else {\n        Ok(format!("用户{}", id))\n    }\n}\n\nfn main() {\n    match find_user(0) {\n        Ok(name) => println!("找到: {}", name),\n        Err(e) => println!("错误: {}", e),\n    }\n}\n', "hint": "用 enum 定义错误变体，实现 `fmt::Display`，在 match 中用 `write!` 输出"},
    ]

    ch9 = db.query(Chapter).filter(Chapter.slug == "ch09-collections").first()
    exercises_ch9 = [
        {"chapter_id": ch9.id, "order": 1, "type": "free", "title": "词频统计", "description": "用 HashMap 统计一段文本中每个单词出现的次数。", "template_code": 'use std::collections::HashMap;\n\nfn word_count(text: &str) -> HashMap<&str, u32> {\n    // 你的实现\n    \n}\n\nfn main() {\n    let text = "hello world hello rust hello world";\n    let counts = word_count(text);\n    for (word, count) in &counts {\n        println!("{}: {}", word, count);\n    }\n}\n', "test_code": "", "solution_code": 'use std::collections::HashMap;\n\nfn word_count(text: &str) -> HashMap<&str, u32> {\n    let mut map = HashMap::new();\n    for word in text.split_whitespace() {\n        *map.entry(word).or_insert(0) += 1;\n    }\n    map\n}\n\nfn main() {\n    let text = "hello world hello rust hello world";\n    let counts = word_count(text);\n    for (word, count) in &counts {\n        println!("{}: {}", word, count);\n    }\n}\n', "hint": "用 `HashMap::new()` 创建，`.entry().or_insert(0)` 获取或初始化计数"},
        {"chapter_id": ch9.id, "order": 2, "type": "fix", "title": "Vec 借用冲突", "description": "代码在遍历 Vec 时尝试修改它，修复借用冲突。", "template_code": 'fn main() {\n    let mut numbers = vec![1, 2, 3, 4, 5];\n    for num in &numbers {\n        if *num > 3 {\n            numbers.push(*num * 10);\n        }\n    }\n    println!("{:?}", numbers);\n}\n', "test_code": "", "solution_code": 'fn main() {\n    let mut numbers = vec![1, 2, 3, 4, 5];\n    let extras: Vec<i32> = numbers.iter().filter(|&&x| x > 3).map(|&x| x * 10).collect();\n    numbers.extend(extras);\n    println!("{:?}", numbers);\n}\n', "hint": "不能在不可变遍历时 push。先收集要添加的元素，再 extend"},
    ]

    ch10 = db.query(Chapter).filter(Chapter.slug == "ch10-generics").first()
    exercises_ch10 = [
        {"chapter_id": ch10.id, "order": 1, "type": "free", "title": "泛型最大值函数", "description": "实现一个泛型函数，返回两个值中较大的那个。", "template_code": '// 实现泛型函数 max_val\n\n\nfn main() {\n    println!("max(3, 7) = {}", max_val(3, 7));\n    println!("max(3.14, 2.71) = {}", max_val(3.14, 2.71));\n    println!("max(a, z) = {}", max_val(\'a\', \'z\'));\n}\n', "test_code": "", "solution_code": 'fn max_val<T: PartialOrd>(a: T, b: T) -> T {\n    if a > b { a } else { b }\n}\n\nfn main() {\n    println!("max(3, 7) = {}", max_val(3, 7));\n    println!("max(3.14, 2.71) = {}", max_val(3.14, 2.71));\n    println!("max(a, z) = {}", max_val(\'a\', \'z\'));\n}\n', "hint": "用 `<T: PartialOrd>` 约束泛型，表示 T 必须支持比较"},
        {"chapter_id": ch10.id, "order": 2, "type": "free", "title": "泛型 Stack", "description": "实现一个泛型 Stack<T>，支持 push、pop、peek 和 is_empty。", "template_code": '// 实现泛型 Stack<T>\nstruct Stack<T> {\n    // 定义字段\n}\n\nimpl<T> Stack<T> {\n    fn new() -> Self { todo!() }\n    fn push(&mut self, item: T) { todo!() }\n    fn pop(&mut self) -> Option<T> { todo!() }\n    fn is_empty(&self) -> bool { todo!() }\n}\n\nfn main() {\n    let mut s = Stack::new();\n    s.push(1);\n    s.push(2);\n    s.push(3);\n    while let Some(val) = s.pop() {\n        println!("pop: {}", val);\n    }\n}\n', "test_code": "", "solution_code": 'struct Stack<T> {\n    elements: Vec<T>,\n}\n\nimpl<T> Stack<T> {\n    fn new() -> Self {\n        Stack { elements: Vec::new() }\n    }\n    fn push(&mut self, item: T) {\n        self.elements.push(item);\n    }\n    fn pop(&mut self) -> Option<T> {\n        self.elements.pop()\n    }\n    fn is_empty(&self) -> bool {\n        self.elements.is_empty()\n    }\n}\n\nfn main() {\n    let mut s = Stack::new();\n    s.push(1);\n    s.push(2);\n    s.push(3);\n    while let Some(val) = s.pop() {\n        println!("pop: {}", val);\n    }\n}\n', "hint": "内部用 `Vec<T>` 存储元素，pop 直接调用 `Vec::pop()`"},
    ]

    ch11 = db.query(Chapter).filter(Chapter.slug == "ch11-traits").first()
    exercises_ch11 = [
        {"chapter_id": ch11.id, "order": 1, "type": "free", "title": "实现 Display trait", "description": "为结构体实现 Display trait，使其可以用 `{}` 打印。", "template_code": 'use std::fmt;\n\nstruct Color {\n    r: u8,\n    g: u8,\n    b: u8,\n}\n\n// 为 Color 实现 Display trait\n\n\nfn main() {\n    let red = Color { r: 255, g: 0, b: 0 };\n    println!("颜色: {}", red);\n}\n', "test_code": "", "solution_code": 'use std::fmt;\n\nstruct Color {\n    r: u8,\n    g: u8,\n    b: u8,\n}\n\nimpl fmt::Display for Color {\n    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {\n        write!(f, "RGB({}, {}, {})", self.r, self.g, self.b)\n    }\n}\n\nfn main() {\n    let red = Color { r: 255, g: 0, b: 0 };\n    println!("颜色: {}", red);\n}\n', "hint": "实现 `impl fmt::Display for Color`，在 `fmt` 方法中用 `write!` 宏"},
        {"chapter_id": ch11.id, "order": 2, "type": "free", "title": "Trait 作参数", "description": "定义 Printable trait，实现一个函数接收任何实现了 Printable 的类型。", "template_code": '// 定义 Printable trait，要求实现 print() 方法\n\n\nstruct Book {\n    title: String,\n}\n\nstruct Article {\n    headline: String,\n}\n\n// 为 Book 和 Article 实现 Printable\n\n\n// 实现一个接收 &impl Printable 的函数\n\n\nfn main() {\n    let book = Book { title: "Rust 编程".to_string() };\n    let article = Article { headline: "Rust 2.0 发布".to_string() };\n    print_item(&book);\n    print_item(&article);\n}\n', "test_code": "", "solution_code": 'trait Printable {\n    fn print(&self);\n}\n\nstruct Book {\n    title: String,\n}\n\nstruct Article {\n    headline: String,\n}\n\nimpl Printable for Book {\n    fn print(&self) {\n        println!("[书] {}", self.title);\n    }\n}\n\nimpl Printable for Article {\n    fn print(&self) {\n        println!("[文章] {}", self.headline);\n    }\n}\n\nfn print_item(item: &impl Printable) {\n    item.print();\n}\n\nfn main() {\n    let book = Book { title: "Rust 编程".to_string() };\n    let article = Article { headline: "Rust 2.0 发布".to_string() };\n    print_item(&book);\n    print_item(&article);\n}\n', "hint": "用 `trait Printable { fn print(&self); }` 定义，`fn print_item(item: &impl Printable)` 接收参数"},
    ]

    ch12 = db.query(Chapter).filter(Chapter.slug == "ch12-closures-iterators").first()
    exercises_ch12 = [
        {"chapter_id": ch12.id, "order": 1, "type": "free", "title": "迭代器链式操作", "description": "用迭代器从数字列表中筛选偶数、平方、求和。", "template_code": 'fn main() {\n    let numbers = vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10];\n    \n    // 用迭代器链：筛选偶数 → 平方 → 求和\n    let result: i32 = /* 你的迭代器链 */;\n    \n    println!("偶数平方和 = {}", result); // 应输出 220\n}\n', "test_code": "", "solution_code": 'fn main() {\n    let numbers = vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10];\n    let result: i32 = numbers.iter()\n        .filter(|&&x| x % 2 == 0)\n        .map(|&x| x * x)\n        .sum();\n    println!("偶数平方和 = {}", result);\n}\n', "hint": "用 `.iter().filter().map().sum()` 链式调用"},
        {"chapter_id": ch12.id, "order": 2, "type": "free", "title": "闭包排序", "description": "用闭包对结构体 Vec 按不同字段排序。", "template_code": 'struct Student {\n    name: String,\n    score: u32,\n}\n\nfn main() {\n    let mut students = vec![\n        Student { name: "Alice".to_string(), score: 85 },\n        Student { name: "Bob".to_string(), score: 92 },\n        Student { name: "Charlie".to_string(), score: 78 },\n    ];\n    \n    // 用闭包按分数降序排序\n    // students.sort_by(|a, b| ...);\n    \n    for s in &students {\n        println!("{}: {}", s.name, s.score);\n    }\n}\n', "test_code": "", "solution_code": 'struct Student {\n    name: String,\n    score: u32,\n}\n\nfn main() {\n    let mut students = vec![\n        Student { name: "Alice".to_string(), score: 85 },\n        Student { name: "Bob".to_string(), score: 92 },\n        Student { name: "Charlie".to_string(), score: 78 },\n    ];\n    students.sort_by(|a, b| b.score.cmp(&a.score));\n    for s in &students {\n        println!("{}: {}", s.name, s.score);\n    }\n}\n', "hint": "用 `sort_by(|a, b| b.score.cmp(&a.score))` 降序排列"},
    ]

    ch13 = db.query(Chapter).filter(Chapter.slug == "ch13-modules").first()
    exercises_ch13 = [
        {"chapter_id": ch13.id, "order": 1, "type": "output", "title": "模块可见性", "description": "阅读代码，判断哪些能编译通过。", "template_code": 'mod my_module {\n    pub fn public_fn() {\n        println!("public");\n        private_fn();\n    }\n\n    fn private_fn() {\n        println!("private");\n    }\n}\n\nfn main() {\n    my_module::public_fn();\n    // my_module::private_fn(); // 这行能编译吗？\n}\n', "test_code": "", "solution_code": "public\nprivate", "hint": "`pub` 标记的函数可以外部访问，没标记的只能模块内部访问"},
        {"chapter_id": ch13.id, "order": 2, "type": "fill", "title": "use 导入", "description": "补全 use 语句，使代码编译通过。", "template_code": 'use std::collections::/* 填入 */;\nuse std::/* 填入 */::HashMap;\n\nfn main() {\n    let mut map = HashMap::new();\n    map.insert("key", 42);\n    let val = map.get("key").unwrap_or(&0);\n    println!("value = {}", val);\n}\n', "test_code": "", "solution_code": 'use std::collections::HashMap;\n\nfn main() {\n    let mut map = HashMap::new();\n    map.insert("key", 42);\n    let val = map.get("key").unwrap_or(&0);\n    println!("value = {}", val);\n}\n', "hint": "HashMap 在 `std::collections` 模块中"},
    ]

    ch14 = db.query(Chapter).filter(Chapter.slug == "ch14-cargo-ecosystem").first()
    exercises_ch14 = [
        {"chapter_id": ch14.id, "order": 1, "type": "output", "title": "Cargo.toml 解析", "description": "阅读 Cargo.toml 配置，判断 cargo build 的行为。", "template_code": '// 假设 Cargo.toml 内容如下：\n// [package]\n// name = "myapp"\n// version = "0.1.0"\n// edition = "2021"\n// [dependencies]\n// serde = { version = "1", features = ["derive"] }\n// [features]\n// extra = ["serde/derive"]\n\nfn main() {\n    println!("cargo features 题");\n    println!("serde derive = enabled");\n}\n', "test_code": "", "solution_code": "cargo features 题\nserde derive = enabled", "hint": "features 是条件编译的特性开关"},
        {"chapter_id": ch14.id, "order": 2, "type": "output", "title": "Cargo 命令", "description": "阅读描述，判断使用哪个 cargo 命令。", "template_code": '// 问题：以下场景分别用什么 cargo 命令？\n// 1. 只编译不运行\n// 2. 运行所有测试\n// 3. 检查代码风格\n// 4. 生成文档\n\nfn main() {\n    println!("build");\n    println!("test");\n    println!("clippy");\n    println!("doc --open");\n}\n', "test_code": "", "solution_code": "build\ntest\nclippy\ndoc --open", "hint": "cargo build / test / clippy / doc"},
    ]

    ch15 = db.query(Chapter).filter(Chapter.slug == "ch15-stage-project").first()
    exercises_ch15 = [
        {"chapter_id": ch15.id, "order": 1, "type": "free", "title": "阶段项目：Word Counter", "description": "综合运用前14章知识，实现一个命令行词频统计工具。统计输入文本中每个单词的出现次数，按频率降序排列。", "template_code": 'use std::collections::HashMap;\n\n/// 统计词频并按频率降序排列\nfn word_frequency(text: &str) -> Vec<(String, u32)> {\n    // 你的实现\n    // 1. 分词\n    // 2. 用 HashMap 统计\n    // 3. 转成 Vec 并排序\n    todo!()\n}\n\nfn main() {\n    let text = "the quick brown fox jumps over the lazy dog the fox the";\n    let freq = word_frequency(text);\n    for (word, count) in freq {\n        println!("{:>10}: {}", word, count);\n    }\n}\n', "test_code": "", "solution_code": 'use std::collections::HashMap;\n\nfn word_frequency(text: &str) -> Vec<(String, u32)> {\n    let mut map = HashMap::new();\n    for word in text.split_whitespace() {\n        *map.entry(word.to_lowercase()).or_insert(0) += 1;\n    }\n    let mut vec: Vec<_> = map.into_iter().map(|(k, v)| (k, v)).collect();\n    vec.sort_by(|a, b| b.1.cmp(&a.1));\n    vec\n}\n\nfn main() {\n    let text = "the quick brown fox jumps over the lazy dog the fox the";\n    let freq = word_frequency(text);\n    for (word, count) in freq {\n        println!("{:>10}: {}", word, count);\n    }\n}\n', "hint": "综合使用 HashMap、Vec、迭代器、排序"},
    ]

    # Ch16-18 (stage 2 placeholders)
    ch16 = db.query(Chapter).filter(Chapter.slug == "ch16-smart-pointers").first()
    exercises_ch16 = [
        {"chapter_id": ch16.id, "order": 1, "type": "free", "title": "Box 递归类型", "description": "用 Box 实现一个简单的链表。", "template_code": '// 用 Box 实现递归链表\nenum List {\n    // 定义链表节点\n}\n\nfn main() {\n    // 创建链表 1 -> 2 -> 3\n    println!("Box 递归类型练习");\n}\n', "test_code": "", "solution_code": 'enum List {\n    Cons(i32, Box<List>),\n    Nil,\n}\n\nfn main() {\n    let list = List::Cons(1, Box::new(List::Cons(2, Box::new(List::Cons(3, Box::new(List::Nil))))));\n    println!("Box 递归类型练习");\n}\n', "hint": "用 `Box<List>` 包装递归成员"},
        {"chapter_id": ch16.id, "order": 2, "type": "output", "title": "Rc 引用计数", "description": "阅读代码，预测 Rc 的强引用计数。", "template_code": 'use std::rc::Rc;\n\nfn main() {\n    let a = Rc::new(5);\n    println!("count after a = {}", Rc::strong_count(&a));\n    let b = Rc::clone(&a);\n    println!("count after b = {}", Rc::strong_count(&a));\n    {\n        let c = Rc::clone(&a);\n        println!("count after c = {}", Rc::strong_count(&a));\n    }\n    println!("count after c dropped = {}", Rc::strong_count(&a));\n}\n', "test_code": "", "solution_code": "count after a = 1\ncount after b = 2\ncount after c = 3\ncount after c dropped = 2", "hint": "Rc::clone 增加引用计数，drop 减少计数"},
    ]

    ch17 = db.query(Chapter).filter(Chapter.slug == "ch17-interior-mutability").first()
    exercises_ch17 = [
        {"chapter_id": ch17.id, "order": 1, "type": "output", "title": "RefCell 基础", "description": "阅读代码，预测输出。", "template_code": 'use std::cell::RefCell;\n\nfn main() {\n    let data = RefCell::new(5);\n    *data.borrow_mut() += 10;\n    println!("data = {}", data.borrow());\n}\n', "test_code": "", "solution_code": "data = 15", "hint": "RefCell 在运行时检查借用规则"},
        {"chapter_id": ch17.id, "order": 2, "type": "free", "title": "Cell 计数器", "description": "用 Cell 实现一个不需要 mut 的计数器。", "template_code": 'use std::cell::Cell;\n\nstruct Counter {\n    count: Cell<u32>,\n}\n\nimpl Counter {\n    fn new() -> Self {\n        // 初始化\n    }\n    fn increment(&self) {\n        // 注意：不需要 &mut self\n    }\n    fn get(&self) -> u32 {\n        // 返回当前计数\n    }\n}\n\nfn main() {\n    let c = Counter::new();\n    c.increment();\n    c.increment();\n    c.increment();\n    println!("count = {}", c.get()); // 应输出 3\n}\n', "test_code": "", "solution_code": 'use std::cell::Cell;\n\nstruct Counter {\n    count: Cell<u32>,\n}\n\nimpl Counter {\n    fn new() -> Self {\n        Counter { count: Cell::new(0) }\n    }\n    fn increment(&self) {\n        self.count.set(self.count.get() + 1);\n    }\n    fn get(&self) -> u32 {\n        self.count.get()\n    }\n}\n\nfn main() {\n    let c = Counter::new();\n    c.increment();\n    c.increment();\n    c.increment();\n    println!("count = {}", c.get());\n}\n', "hint": "Cell::set() 设置值，Cell::get() 获取值（要求 Copy 类型）"},
    ]

    ch18 = db.query(Chapter).filter(Chapter.slug == "ch18-concurrency").first()
    exercises_ch18 = [
        {"chapter_id": ch18.id, "order": 1, "type": "free", "title": "多线程求和", "description": "用多线程计算 1 到 100 的和。", "template_code": 'use std::thread;\n\nfn main() {\n    // 将 1..=100 分成多段，每段一个线程求和\n    // 最后汇总结果\n    \n}\n', "test_code": "", "solution_code": 'use std::thread;\n\nfn main() {\n    let mut handles = vec![];\n    for chunk_start in (1..=100).step_by(25) {\n        let handle = thread::spawn(move || {\n            let end = std::cmp::min(chunk_start + 25, 101);\n            (chunk_start..end).sum::<i64>()\n        });\n        handles.push(handle);\n    }\n    let total: i64 = handles.into_iter().map(|h| h.join().unwrap()).sum();\n    println!("1 到 100 的和 = {}", total);\n}\n', "hint": "用 `thread::spawn` 创建线程，`handle.join()` 等待结果"},
        {"chapter_id": ch18.id, "order": 2, "type": "free", "title": "Channel 消息传递", "description": "用 mpsc channel 在主线程和子线程之间传递消息。", "template_code": 'use std::sync::mpsc;\nuse std::thread;\n\nfn main() {\n    // 创建 channel\n    // 在子线程中发送 5 条消息\n    // 在主线程中接收并打印\n    \n}\n', "test_code": "", "solution_code": 'use std::sync::mpsc;\nuse std::thread;\n\nfn main() {\n    let (tx, rx) = mpsc::channel();\n    thread::spawn(move || {\n        for i in 1..=5 {\n            tx.send(format!("消息 {}", i)).unwrap();\n            thread::sleep(std::time::Duration::from_millis(100));\n        }\n    });\n    for received in rx {\n        println!("收到: {}", received);\n    }\n}\n', "hint": "用 `mpsc::channel()` 创建，`tx.send()` 发送，`rx` 直接迭代接收"},
    ]

    all_exercises = (
        exercises_ch1 + exercises_ch2 + exercises_ch3 + exercises_ch4 + exercises_ch5 +
        exercises_ch6 + exercises_ch7 + exercises_ch8 + exercises_ch9 + exercises_ch10 +
        exercises_ch11 + exercises_ch12 + exercises_ch13 + exercises_ch14 + exercises_ch15 +
        exercises_ch16 + exercises_ch17 + exercises_ch18
    )
    for ex_data in all_exercises:
        ex = Exercise(**ex_data)
        db.add(ex)

    db.commit()
    print(f"✅ Seeded {len(chapters_data)} chapters, {len(all_exercises)} exercises")
